name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build in Docker and Publish Image
      uses: matootie/github-docker@v2.2.2
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
